### ISSUE TITLE
Кэширование.

### ISSUE THREAD

**Issue by rcd27** [Denis-Gluhov/kino#1]
AppModule: 30: используется new OkHttpClient().
Так как в задаче говорится о кэшировании, советую посмотреть, что предлагает OkHttpClient() для
кэширования и запровайдить его здесь. Там понадобится Context, можно передать в модуль при его создании.

**Comment by Denis-Gluhov** [comment]
Нее, тут имеется в виду хранение в БД, если отсутствует соединение то данные выводить из БД.
